module.exports = {
    name: 'tweet',
    description: 'outputs a random covey/siggy/dan tweet',
    execute(message){
        const siggy = '<:Siggy:909631771820326973>';
        const dan = '<:Mr_Nauseous:909631726408581191>';
        const covey = '<:covhappy:826907997682663474>';
        const danInd = 74;
        const covInd = 88;

        const tweets = [
            "live laugh ugh",
            "i think we need some new shapes",
            "a reality identical to ours except socks and potatoes are switched",
            "what if we 🥺👉👈 kissed 😭 in the 𝔠𝔬𝔪𝔭𝔲𝔱𝔢𝔯 𝔫𝔢𝔢𝔡𝔰 section of Rite Aid 😔😩",
            "jesus was a gamer",
            "let me tell you how good i got at spelling 'nauseous'",
            "if you tell me you don't like folding laundry i'm immediately going to have several followup questions",
            "some personal news: i am going through it",
            "i like when my friends in relationships vote opposite their partner in my insta story polls, that's nice",
            "a pro-gamer move would be to name your pet after a food you hate",
            "reverse future",
            "what does shade taste like?",
            "you got me fucked up if you think im going to create ann account on good h*usekeeping dot com to read an article about DIY solutions to kill fruit flies miss me with that every single time",
            "can't wait to meet and hangout with an AI version of myself in VR - the ultimate social distancing",
            "my dream brand collaboration would be with juicy fruit",
            "business idea: vr for cats",
            "neighbor who i've spoken to once in my one year of living in my current building rang my door bell asking to borrow a can opener. they were in luck because i have a sick can opener. its all magnetic and shit",
            "yogurt is just morning ice cream",
            "if you're dating a coder you're single to me. what're they gonna do? dress in all black and write bespoke instructions for computer?",
            "i sent an email at work today i think",
            "shouting \"calorie defecit\" at the melting ice caps",
            "thinking about the pink clouds aesthetic",
            "looking forward to the next lorde album",
            "legalize ranch",
            "\"describe software engineering in three words or less\" \"alive. ahaha. fuck.\"",
            "be grateful to be small",
            "http got me like ://",
            "im about to mute the word turnip",
            "the twilight movie is SO bAD",
            "this is the Diet Coke of vampire movies",
            "low key used to be a little freaked out by my parents basement. now i spent like 14 hours a day there",
            "it's 6:06pm time time to change into my outdoor sweatpants and go outside to look at a tree or something - there's a whole world out there",
            "i start every video call meeting with a heart \"hey what's up YouTube!?\"",
            "pineappleblueberry",
            "stuff really out here taking time to do",
            "something about being in the suburbs just makes me wanna drink soda idk man",
            "why does it take seven days and seven nights to get olive oil off my hands",
            "do you have an eye 𝒻𝑜𝓇 𝒹𝑒𝓈𝒾𝑔𝓃 ?",
            "me, at work, at 11:27am: [eyes going black] **ⱠɄ₦₵Ⱨ**",
            "happy national banana bread day",
            "i have to exercise a lot of restraint to not drink more than 2 la croixs per day",
            "gonna start Randomly Capitalizing Words, as a Personality Trait",
            "did anyone ever really have an iphone 8??",
            "y'all think my house plants would fw la croix over sink water? be honest..",
            "i'm pre-viral pre-verrified for the time being here on twitter dot com",
            "defining variables using let and const got me feelin like on some Shakespeare vibe fr bruh",
            "in college i would drink mountain dew for breakfast",
            "when yung lean said: \"fuck everyone i don't reply, sad bois were worldwide\" i really felt that",
            "don't own a broom",
            "normal person: \"do you like yoga?\" \n me, at work: \"do you fuck with yoga?\"",
            "listening to shark smile, folding laundry, literally just vibing",
            "just got new jeans and they are so stiff. they are the only thing keeping me upright 😩",
            "life is crazy mane you can do anything, you can go anywhere. you can get shtoned and chop garlic. that's what i'm doing",
            "dudes got demons but never been to Des Moines, Iowa",
            "fyi i was the first person ever to end a song by turning the beat half speed, no one else had done that before i did it in 2016",
            "band name idea: Long Term Capital Gains Liquidation Event",
            "easy weight loss tip: haircut",
            "my second shower of the decade was a massive success",
            "soda for dogs is actually a billion dollar untapped market",
            "you know how to balance but i don't",
            "in the opening credits of Elf, is that a penguin or a puffin? penguins are only available at the south pole you know",
            "it's the end of the year. it's the end of the decade. people are slowing down. folks are recharging. not me. i'm edgy. i'm different. i'm starting a fashion brand and it's coming soon. youngandnauseo.us",
            "taking the L for the first time in months. forgot about this energy tbh",
            "reverse microwave",
            "Welcome to the Black Parade is a christmas song because it has sleigh bells in it",
            "cell phone",
            "pillow vibes",
            "alternative 400 Coffee's lyrics: \"I need, 400 loads of laundry\"",
            "skrr skrr to the moon i'm swervin",
            "when yung lean doer said: \"emotional boys 2012\" i really felt that",
            "is wearing sunglasses on the subway a personality trait?",
            "how much nail polish can i accidentally ingest before it becomes a serious health concern? this shit is all over my hands and im about to eat food",
            "if i could wake up and do one thing everyday it would be laser tag - instead i sm*ke d*pe, play music, and bang on keyboards",
            "if you eat dry cereal do you reallllly have to clean the bowl? asking for a fwend 🥺",
            "i used to go on twitter dot com and see cats with like 27.3k tweets and be like 😳😳😳 but now i like totalllly get it",
            //end dan tweets, start covey
            "I\'m sorry but if you have to jog to keep up with my normal walking speed, I\'m cutting you from my zombie apocalypse survival team",
            "should we made \"danger five\" themed music video cause i think we should",
            "its lit",
            "Gucci model material?",
            "You\'ll never see me scamble for the remote quicker than when I\'m home alone, and an ad for a scary move comes on...",
            "Had a dream where I fathered a baby sloth called Stretch #oneday",
            "Do you guys get as annoyed as me when a child strokes a dog or cat the opposite direction of its fur?",
            "I loooove drifting on shopping carts as i pick up bananas for the weekend #fruit #tokoyodrift",
            "I can\'t think of a tweet right now...The creative juices aren\'t flowing",
            "what if we didn\'t have fingers on one of our hands, it was just a spade type shape. It would be like a giant spoon.",
            "I have come to the conclusion that dryer lint is the cremated remains of all my missing socks #wheredotheygo #RIPsocks",
            "Make some room, then consume.",
            "Friday night! Let's go break into a traveling circus",
            "High love and emotion",
            "we are now cobey",
            //end covey tweets, start siggy
            "Pop punk is to America as Brit pop is to the uk",
            "Slippery joe",
            "Experimental snack bar",
            "Holding my friends by the hand and walking them through twin peaks we just finished season 1 I\'m proud of them",
            "hip hope",
            "I will not let you speak, I will interrupt you and I'll entertain you because you can\'t entertain me",
            "Love is biased",
            "Nothing compares to the feeling of farting in the control room",
            "I believe in justice but no one believes in me",
            "I don\'t suffer from human emotion",
            "Saturday night people crying in the streets of bushwick",
            "I live at the DMV now",
            "I can hear the babies cry through my noise cancelling earbuds where is this plane taking me",
            "Got a fart in my stomach... Just pierced my stomach, the fart has been freed",
            "Egg cake",
            "If you wanna be proactive you have to start blaming things on other people",
            "Contrary to popular belief I should take a shower",
            "I have to do everything in this house I have to clean my own feet",
            "I\'m not superstitious or anything but if don\'t have coffee I don\'t enjoy things",
            "Pretzel Butter",
            "Adults were so big back in the day",
            "Post rock minus shoegaze equals slowcore",
            "Shakira voices Kermit the frog",
            "Monster cheese",
            "I don\'t have goals because that\'s stressful",
            "Joel Biden",
            "professional edgelord",
            "Smooch elevator",
            "The opposite of eating is brushing teeth",
            "Homegrown hair",
            "I don\'t trust new music",
            "My toes are getting bigger and bigger",
            "Mayo bath",
            "So little time and so much poop",
            "There was way more poop than there was me. I was outnumbered. I feared that if I flushed it would take me with it",
            "I don\'t take phone calls after 9",
            "Sloppy jane themed d&d campaign",
            "Twitter juice",
            "One toothbrush, two teethbrush",
            "Beeps per minute",
            "Brush your teeth or go to jail",
            "Pirate aesthetic",
            "Growing out my fingers so I can covid-test myself",
            "Transparent toaster",
            "Olive milk",
            "I don\'t even tuck my shirt in anymore idgaf",
            "Rommate barks at spider",
            "Chili is more than the sum of its parts",
            "Turtle always smiling",
            "Chronic urinator",
            "Garbanzo milkshake",
            "I still remember that traumatic day I learned that physical growth stops at a certain age and that for the most part of our lifetime we\'re not getting bigger and bigger",
            "British accent is a tool, a means to an end",
            "How do they count bees?",
            "Fucking hate kangaroos. Portrayed by the media as this cute exotic marsupial but it's really the most demonic creature out there",
            "Eat chili with moderation",
            "I am not only a hoarder of things, I\'m also a hoarder of internet tabs",
            "Mix like your life depended on it. I\'d probably die",
            "The ergonomic design of a banana, curved in the shape of a man\'s grip, goes to show god intended them to be consumed handheld",
            "Shoedive",
            "10 years off popcorn",
            "Floss hard cuz the future is uncertain and u never know if you\'ll be around to floss tomorrow",
            "Weed",
            "Spread cheese, not love",
            "How do I know if I\'ve had enough seaweed?",
            "Finished taking a dump. Blew my nose in front of the mirror and unintentionally raised on eyebrow for the first time ever. Tried it again and it didn\'t work.",
            "Black bean cereal",
            "Broccoli juice",
            "Have you sneezed in public yet? Hahaha",
            "first time i got sued for having the \"peeness\" [condition that makes you pee w frequency.] 6/yo and the preschool psychologist pulled me aside- \"do you know, when you sleep you hold it for 10 hours?\" Patricia, you think I\'m one of those idiots who don\'t pee their beds? HAHAHA!",
            "Use melted cheese to glue things together",
            "It\'s time we start using melted cheese as glue",
            "Years ago I had a near-death experience with fish",
            "Sliced onions and regular milk",
            "Once upon a time toilet paper didn't exist, now people peel tomatoes",
            "Fingertips in the eyeballs\n\n(This tweet is brought to you in collaboration with Dan Hemerlein)",
            "Is it not proof of god\'s benevolent tinkering that, of all living creatures, only the human is capable of complaining"
        ];

        let len = tweets.length;
        let rand = Math.floor(Math.random()*(len));
        let face = (rand <= danInd) ? dan : (rand > covInd) ? siggy : covey;
        message.channel.send(face + "*" + tweets[rand] + "*" + face);

        console.log(tweets[74]);
        console.log(tweets[88]);
    }
}