module.exports = {
    name: 'tweet',
    description: 'outputs a random covey/siggy/dan tweet',
    execute(message){
        const siggy = '<:Siggy:909631771820326973>';
        const dan = '<:Mr_Nauseous:909631726408581191>';
        const covey = '<:covhappy:826907997682663474>';
        
        const tweets = new Map();
        tweets.set("live laugh ugh", "dan");
        tweets.set("i think we need some new shapes", "dan");
        tweets.set("a reality identical to ours except socks and potatoes are switched", "dan");
        tweets.set("what if we 🥺👉👈 kissed 😭 in the 𝔠𝔬𝔪𝔭𝔲𝔱𝔢𝔯 𝔫𝔢𝔢𝔡𝔰 section of Rite Aid 😔😩", "dan");
        tweets.set("jesus was a gamer", "dan");
        tweets.set("let me tell you how good i got at spelling \`nauseous\`", "dan");
        tweets.set("if you tell me you don't like folding laundry i'm immediately going to have several followup questions", "dan");
        tweets.set("some personal news: i am going through it", "dan");
        tweets.set("i like when my friends in relationships vote opposite their partner in my insta story polls, that's nice", "dan");
        tweets.set("a pro-gamer move would be to name your pet after a food you hate", "dan");
        tweets.set("reverse future", "dan");
        tweets.set("what does shade taste like?", "dan");
        tweets.set("you got me fucked up if you think im going to create ann account on good h*usekeeping dot com to read an article about DIY solutions to kill fruit flies miss me with that every single time", "dan");
        tweets.set("can't wait to meet and hangout with an AI version of myself in VR - the ultimate social distancing", "dan");
        tweets.set("my dream brand collaboration would be with juicy fruit", "dan");
        tweets.set("business idea: vr for cats", "dan");
        tweets.set("neighbor who i've spoken to once in my one year of living in my current building rang my door bell asking to borrow a can opener. they were in luck because i have a sick can opener. its all magnetic and shit", "dan");
        tweets.set("yogurt is just morning ice cream", "dan");
        tweets.set("if you're dating a coder you're single to me. what're they gonna do? dress in all black and write bespoke instructions for computer?", "dan");
        tweets.set("i sent an email at work today i think", "dan");
        tweets.set("shouting \"calorie defecit\" at the melting ice caps", "dan");
        tweets.set("thinking about the pink clouds aesthetic", "dan");
        tweets.set("looking forward to the next lorde album", "dan");
        tweets.set("legalize ranch", "dan");
        tweets.set("\"describe software engineering in three words or less\" \"alive. ahaha. fuck.\"", "dan");
        tweets.set("be grateful to be small", "dan");
        tweets.set("http got me like ://", "dan");
        tweets.set("im about to mute the word turnip", "dan");
        tweets.set("the twilight movie is SO bAD", "dan");
        tweets.set("this is the Diet Coke of vampire movies", "dan");
        tweets.set("low key used to be a little freaked out by my parents basement. now i spent like 14 hours a day there", "dan");
        tweets.set("it's 6:06pm time time to change into my outdoor sweatpants and go outside to look at a tree or something - there's a whole world out there", "dan");
        tweets.set("i start every video call meeting with a heart \"hey what's up YouTube!?\"", "dan");
        tweets.set("pineappleblueberry", "dan");
        tweets.set("stuff really out here taking time to do", "dan");
        tweets.set("something about being in the suburbs just makes me wanna drink soda idk man", "dan");
        tweets.set("why does it take seven days and seven nights to get olive oil off my hands", "dan");
        tweets.set("do you have an eye 𝒻𝑜𝓇 𝒹𝑒𝓈𝒾𝑔𝓃 ?", "dan");
        tweets.set("me, at work, at 11:27am: [eyes going black] **ⱠɄ₦₵Ⱨ**", "dan");
        tweets.set("happy national banana bread day", "dan");
        tweets.set("i have to exercise a lot of restraint to not drink more than 2 la croixs per day", "dan");
        tweets.set("gonna start Randomly Capitalizing Words, as a Personality Trait", "dan");
        tweets.set("did anyone ever really have an iphone 8??", "dan");
        tweets.set("y'all think my house plants would fw la croix over sink water? be honest..", "dan");
        tweets.set("i'm pre-viral pre-verrified for the time being here on twitter dot com", "dan");
        tweets.set("defining variables using let and const got me feelin like on some Shakespeare vibe fr bruh", "dan");
        tweets.set("in college i would drink mountain dew for breakfast", "dan");
        tweets.set("when yung lean said: \"fuck everyone i don't reply, sad bois were worldwide\" i really felt that", "dan");
        tweets.set("don't own a broom", "dan");
        tweets.set("normal person: \"do you like yoga?\" \n me, at work: \"do you fuck with yoga?\"", "dan");
        tweets.set("listening to shark smile, folding laundry, literally just vibing", "dan");
        tweets.set("just got new jeans and they are so stiff. they are the only thing keeping me upright 😩", "dan");
        tweets.set("life is crazy mane you can do anything, you can go anywhere. you can get shtoned and chop garlic. that's what i'm doing", "dan");
        tweets.set("dudes got demons but never been to Des Moines, Iowa", "dan");
        tweets.set("fyi i was the first person ever to end a song by turning the beat half speed, no one else had done that before i did it in 2016", "dan");
        tweets.set("band name idea: Long Term Capital Gains Liquidation Event", "dan");
        tweets.set("easy weight loss tip: haircut", "dan");
        tweets.set("my second shower of the decade was a massive success", "dan");
        tweets.set("soda for dogs is actually a billion dollar untapped market", "dan");
        tweets.set("you know how to balance but i don't", "dan");
        tweets.set("in the opening credits of Elf, is that a penguin or a puffin? penguins are only available at the south pole you know", "dan");
        tweets.set("it's the end of the year. it's the end of the decade. people are slowing down. folks are recharging. not me. i'm edgy. i'm different. i'm starting a fashion brand and it's coming soon. youngandnauseo.us", "dan");
        tweets.set("taking the L for the first time in months. forgot about this energy tbh", "dan");
        tweets.set("reverse microwave", "dan");
        tweets.set("Welcome to the Black Parade is a christmas song because it has sleigh bells in it", "dan");
        tweets.set("cell phone", "dan");
        tweets.set("pillow vibes", "dan");
        tweets.set("alternative 400 Coffee's lyrics: \"I need, 400 loads of laundry\"", "dan");
        tweets.set("skrr skrr to the moon i'm swervin", "dan");
        tweets.set("when yung lean doer said: \"emotional boys 2012\" i really felt that", "dan");
        tweets.set("is wearing sunglasses on the subway a personality trait?", "dan");
        tweets.set("how much nail polish can i accidentally ingest before it becomes a serious health concern? this shit is all over my hands and im about to eat food", "dan");
        tweets.set("if i could wake up and do one thing everyday it would be laser tag - instead i sm*ke d*pe, play music, and bang on keyboards", "dan");
        tweets.set("if you eat dry cereal do you reallllly have to clean the bowl? asking for a fwend 🥺", "dan");
        tweets.set("i used to go on twitter dot com and see cats with like 27.3k tweets and be like 😳😳😳 but now i like totalllly get it", "dan");


        tweets.set("I\'m sorry but if you have to jog to keep up with my normal walking speed, I\'m cutting you from my zombie apocalypse survival team", "covey");
        tweets.set("should we made \"danger five\" themed music video cause i think we should", "covey");
        tweets.set("its lit", "covey");
        tweets.set("Gucci model material?", "covey");
        tweets.set("You\'ll never see me scamble for the remote quicker than when I\'m home alone, and an ad for a scary move comes on...", "covey");
        tweets.set("Had a dream where I fathered a baby sloth called Stretch #oneday", "covey");
        tweets.set("Do you guys get as annoyed as me when a child strokes a dog or cat the opposite direction of its fur?", "covey");
        tweets.set("I loooove drifting on shopping carts as i pick up bananas for the weekend #fruit #tokoyodrift", "covey");
        tweets.set("I can\'t think of a tweet right now...The creative juices aren\'t flowing", "covey");
        tweets.set("what if we didn\'t have fingers on one of our hands, it was just a spade type shape. It would be like a giant spoon.", "covey");
        tweets.set("I have come to the conclusion that dryer lint is the cremated remains of all my missing socks #wheredotheygo #RIPsocks", "covey");
        tweets.set("Make some room, then consume.", "covey");
        tweets.set("Friday night! Let's go break into a traveling circus", "covey");
        tweets.set("High love and emotion", "covey");
        tweets.set("we are now cobey", "covey");
        
        tweets.set("Pop punk is to America as Brit pop is to the uk", "siggy");
        tweets.set("Slippery joe", "siggy");
        tweets.set("Experimental snack bar", "siggy");
        tweets.set("Holding my friends by the hand and walking them through twin peaks we just finished season 1 I\'m proud of them", "siggy"); 
        tweets.set("hip hope", "siggy");
        tweets.set("I will not let you speak, I will interrupt you and I'll entertain you because you can\'t entertain me", "siggy");
        tweets.set("Love is biased", "siggy");
        tweets.set("Nothing compares to the feeling of farting in the control room", "siggy");
        tweets.set("I believe in justice but no one believes in me", "siggy");
        tweets.set("I don\'t suffer from human emotion", "siggy");
        tweets.set("Saturday night people crying in the streets of bushwick", "siggy");
        tweets.set("I live at the DMV now", "siggy");
        tweets.set("I can hear the babies cry through my noise cancelling earbuds where is this plane taking me", "siggy");
        tweets.set("Got a fart in my stomach... Just pierced my stomach, the fart has been freed", "siggy");
        tweets.set("Egg cake", "siggy");
        tweets.set("If you wanna be proactive you have to start blaming things on other people", "siggy");
        tweets.set("Contrary to popular belief I should take a shower", "siggy");
        tweets.set("I have to do everything in this house I have to clean my own feet", "siggy");
        tweets.set("I\'m not superstitious or anything but if don\'t have coffee I don\'t enjoy things", "siggy");
        tweets.set("Pretzel Butter", "siggy");
        tweets.set("Adults were so big back in the day", "siggy");
        tweets.set("Post rock minus shoegaze equals slowcore", "siggy");
        tweets.set("Shakira voices Kermit the frog", "siggy");
        tweets.set("Monster cheese", "siggy");
        tweets.set("I don\'t have goals because that\'s stressful", "siggy");
        tweets.set("Joel Biden", "siggy");
        tweets.set("professional edgelord", "siggy");
        tweets.set("Smooch elevator", "siggy");
        tweets.set("The opposite of eating is brushing teeth", "siggy");
        tweets.set("Homegrown hair", "siggy");
        tweets.set("I don\'t trust new music", "siggy");
        tweets.set("My toes are getting bigger and bigger", "siggy");
        tweets.set("Mayo bath", "siggy");
        tweets.set("So little time and so much poop", "siggy");
        tweets.set("There was way more poop than there was me. I was outnumbered. I feared that if I flushed it would take me with it", "siggy");
        tweets.set("I don\'t take phone calls after 9", "siggy");
        tweets.set("Sloppy jane themed d&d campaign", "siggy");
        tweets.set("Twitter juice", "siggy");
        tweets.set("One toothbrush, two teethbrush", "siggy");
        tweets.set("Beeps per minute", "siggy"); 
        tweets.set("Brush your teeth or go to jail", "siggy");
        tweets.set("Pirate aesthetic", "siggy");
        tweets.set("Growing out my fingers so I can covid-test myself ", "siggy");
        tweets.set("Transparent toaster", "siggy");
        tweets.set("Olive milk", "siggy");
        tweets.set("I don\'t even tuck my shirt in anymore idgaf", "siggy");
        tweets.set("Rommate barks at spider", "siggy");
        tweets.set("Chili is more than the sum of its parts", "siggy");
        tweets.set("Turtle always smiling", "siggy");
        tweets.set("Chronic urinator", "siggy"); 
        tweets.set("Garbanzo milkshake", "siggy");
        tweets.set("I still remember that traumatic day I learned that physical growth stops at a certain age and that for the most part of our lifetime we\'re not getting bigger and bigger", "siggy");
        tweets.set("British accent is a tool, a means to an end", "siggy");
        tweets.set("How do they count bees?", "siggy");
        tweets.set("Fucking hate kangaroos. Portrayed by the media as this cute exotic marsupial but it's really the most demonic creature out there", "siggy"); 
        tweets.set("Eat chili with moderation", "siggy");
        tweets.set("I am not only a hoarder of things, I\'m also a hoarder of internet tabs", "siggy");
        tweets.set("Mix like your life depended on it. I\'d probably die", "siggy");
        tweets.set("The ergonomic design of a banana, curved in the shape of a man\'s grip, goes to show god intended them to be consumed handheld", "siggy");
        tweets.set("Shoedive", "siggy");
        tweets.set("10 years off popcorn", "siggy");
        tweets.set("Floss hard cuz the future is uncertain and u never know if you\'ll be around to floss tomorrow", "siggy");
        tweets.set("Weed", "siggy");
        tweets.set("Spread cheese, not love", "siggy");
        tweets.set("How do I know if I\'ve had enough seaweed?", "siggy");
        tweets.set("Finished taking a dump. Blew my nose in front of the mirror and unintentionally raised on eyebrow for the first time ever. Tried it again and it didn\'t work.", "siggy");
        tweets.set("Black bean cereal", "siggy");
        tweets.set("Broccoli juice", "siggy");
        tweets.set("Have you sneezed in public yet? Hahaha", "siggy");
        tweets.set("first time i got sued for having the \"peeness\" [condition that makes you pee w frequency.] 6/yo and the preschool psychologist pulled me aside- \"do you know, when you sleep you hold it for 10 hours?\"\nPatricia, you think I\'m one of those idiots who don\'t pee their beds?\nHAHAHA!", "siggy");
        tweets.set("Use melted cheese to glue things together", "siggy");
        tweets.set("It\'s time we start using melted cheese as glue", "siggy");
        tweets.set("Years ago I had a near-death experience with fish", "siggy");
        tweets.set("Sliced onions and regular milk", "siggy");
        tweets.set("Once upon a time toilet paper didn't exist, now people peel tomatoes", "siggy");
        tweets.set("Fingertips in the eyeballs\n\n(This tweet is brought to you in collaboration with Dan Hemerlein", "siggy");
        tweets.set("Is it not proof of god\'s benevolent tinkering that, of all living creatures, only the human is capable of complaining ", "siggy");

        tweets.forEach((emote, content) => {
            let face = (emote == 'siggy') ? siggy : (emote == 'covey') ? covey : dan;
            message.channel.send(`${face}${content}${face}`);
        });

        // let len = tweets.length;
        // let rand = Math.floor(Math.random()*(len));
        // message.channel.send(covhappy + "*" + quotes[rand] + "*" + covhappy);
    }
}